// <auto-generated />
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);  // PostgreSQL limite de 63 caracteres para identificadores

            modelBuilder.HasPostgresExtension("uuid-ossp");  // Caso esteja usando UUIDs ou extensões específicas

            modelBuilder.Entity("API.Models.Model_Produtos", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("serial"); // PostgreSQL usa SERIAL para auto incremento

                b.Property<string>("Descricao")
                    .IsRequired()
                    .HasColumnType("text");  // Em PostgreSQL, nvarchar(max) é text

                b.Property<string>("Imagem")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<decimal>("Preco")
                    .HasColumnType("decimal(18,2)");

                b.Property<string>("Produto")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<int>("Quantidade")
                    .HasColumnType("integer");

                b.HasKey("Id");

                b.ToTable("Produtos");
            });

            // Adicionando a tabela Usuarios para PostgreSQL
            modelBuilder.Entity("API.Models.Model_Usuarios", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("serial");  // SERIAL para auto incremento

                b.Property<string>("Nome")
                    .IsRequired()
                    .HasColumnType("varchar(100)");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasColumnType("varchar(100)");

                b.Property<string>("Senha")
                    .IsRequired()
                    .HasColumnType("varchar(255)");

                b.Property<string>("Funcao")
                    .IsRequired()
                    .HasColumnType("varchar(50)");



                b.HasKey("Id");

                b.HasIndex("Email")
                    .IsUnique();

                b.ToTable("Usuarios");
            });
#pragma warning restore 612, 618
        }
    }
}
